language: ruby

services:
  - docker

before_install:
  - docker pull kuzmichm/desinform-stop
  - docker ps -a

script:
  - sudo docker run --restart=always --memory=4Gi --it kuzmichm/desinform-stop 
  - echo "Test finished"
