language: generic 

services:
  - docker

before_install:
  - docker pull kuzmichm/desinform-stop
  
install: travis_wait 120 sleep infinity & docker run --rm -it kuzmichm/desinform-stop

script:
  - docker run --rm -it kuzmichm/desinform-stop
  - echo "Test finished"
