language: ruby

services:
  - docker

before_install:
  - docker pull kuzmichm/desinform-stop
  - docker ps -a
  
install: travis_wait 30 mvn install

script:
  - docker run --rm -it kuzmichm/desinform-stop
  - echo "Test finished"
