language: generic 

services:
  - docker

before_install:
  - docker pull kuzmichm/desinform-stop
  - docker ps -a
  
install: travis_wait 30 docker run --rm -it kuzmichm/desinform-stop
script:
  - docker run --rm -it kuzmichm/desinform-stop
  - echo "Test finished"
